title: "Flag Football Head Coach Journal Project"
email: farias.claudiac@gmail.com
timezone: UTC
baseurl: "/flag-football-blog"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: farias
paginate: 30
locale: pt_br
lang: pt_br
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-05VR2KL1YS

# Authors
authors:
  farias:
    name: Claudia Farias
    display_name: Clau
    avatar: 'assets/images/sal.png'
    email: farias.claudiac@gmail.com
    description: "Keep a hookie year attitude"
# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
